name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # deploy on push to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Install dependencies
      - run: npm ci

      # 4. Build CRA app
      - run: npm run build

      # 5. Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HISTORICAL_DOCS_CHAT_FRONTEND }}
          projectId: historical-docs-chat-frontend
          channelId: live
